### ISSUE TITLE
[JAVA/Eclipse Server] eglot-rename error

### ISSUE THREAD

**Issue by eubarbosa** [joaotavora/eglot#179]
Hey, 

Calling `eglot-rename` in a Java/Eclipse Server buffer with this eg issues that error:

```
int z = 10;
z = 5;
```
**rename 'z' to: b**

```
Debugger entered--Lisp error: (jsonrpc-error "request id=8142 failed:" (jsonrpc-error-code . -32600) (jsonrpc-error-message . "'.' is not a valid Java identifier") (jsonrpc-error-data))
  signal(jsonrpc-error ("request id=8142 failed:" (jsonrpc-error-code . -32600) (jsonrpc-error-message . "'.' is not a valid Java identifier") (jsonrpc-error-data)))
  (progn (signal 'jsonrpc-error (cons (format "request id=%s failed:" (car id-and-timer)) (cdr retval))))
  (if (eq 'error (car retval)) (progn (signal 'jsonrpc-error (cons (format "request id=%s failed:" (car id-and-timer)) (cdr retval)))))
  (let* ((tag (cl-gensym "jsonrpc-request-catch-tag")) id-and-timer cancelled (retval (unwind-protect (catch tag (setq id-and-timer (jsonrpc--async-request-1 connection method params :success-fn (function (lambda (result) (if cancelled nil (throw tag (list 'done result))))) :error-fn (function (lambda (jsonrpc-lambda-elem71) (apply (function (lambda (&rest --cl-rest--) "\n\n(fn &key CODE MESSAGE DATA)" (let* ((code (car (cdr (plist-member --cl-rest-- ':code)))) (message (car (cdr (plist-member --cl-rest-- ':message)))) (data (car (cdr (plist-member --cl-rest-- ':data))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:code :message :data :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:code :message :data)" (car --cl-keys--)))))) (if cancelled nil (throw tag (list 'error (cons 'jsonrpc-error-code code) (cons 'jsonrpc-error-message message) (cons 'jsonrpc-error-data data)))))))) jsonrpc-lambda-elem71))) :timeout-fn (function (lambda nil (if cancelled nil (throw tag '(error (jsonrpc-error-message . "Timed out")))))) :deferred deferred :timeout timeout)) (cond (cancel-on-input (while (sit-for 30)) (setq cancelled t) (list 'cancelled cancel-on-input-retval)) (t (while t (accept-process-output nil 30))))) (let* ((x225 (car id-and-timer)) (x226 (cdr id-and-timer)) (x227 (car x226)) (x228 (cdr x226))) (let ((timer x227) (id x225)) (progn (remhash id (jsonrpc--request-continuations connection)) (remhash (list deferred (current-buffer)) (jsonrpc--deferred-actions connection)) (if timer (progn (cancel-timer timer))))))))) (if (eq 'error (car retval)) (progn (signal 'jsonrpc-error (cons (format "request id=%s failed:" (car id-and-timer)) (cdr retval))))) (car (cdr retval)))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:deferred :timeout :cancel-on-input :cancel-on-input-retval :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:deferred :timeout :cancel-on-input :cancel-on-input-retval)" (car --cl-keys--)))))) (let* ((tag (cl-gensym "jsonrpc-request-catch-tag")) id-and-timer cancelled (retval (unwind-protect (catch tag (setq id-and-timer (jsonrpc--async-request-1 connection method params :success-fn (function (lambda (result) (if cancelled nil (throw tag (list 'done result))))) :error-fn (function (lambda (jsonrpc-lambda-elem71) (apply (function (lambda (&rest --cl-rest--) "\n\n(fn &key CODE MESSAGE DATA)" (let* ((code (car (cdr (plist-member --cl-rest-- ':code)))) (message (car (cdr (plist-member --cl-rest-- ':message)))) (data (car (cdr (plist-member --cl-rest-- ':data))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:code :message :data :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:code :message :data)" (car --cl-keys--)))))) (if cancelled nil (throw tag (list 'error (cons 'jsonrpc-error-code code) (cons 'jsonrpc-error-message message) (cons 'jsonrpc-error-data data)))))))) jsonrpc-lambda-elem71))) :timeout-fn (function (lambda nil (if cancelled nil (throw tag '(error (jsonrpc-error-message . "Timed out")))))) :deferred deferred :timeout timeout)) (cond (cancel-on-input (while (sit-for 30)) (setq cancelled t) (list 'cancelled cancel-on-input-retval)) (t (while t (accept-process-output nil 30))))) (let* ((x225 (car id-and-timer)) (x226 (cdr id-and-timer)) (x227 (car x226)) (x228 (cdr x226))) (let ((timer x227) (id x225)) (progn (remhash id (jsonrpc--request-continuations connection)) (remhash (list deferred (current-buffer)) (jsonrpc--deferred-actions connection)) (if timer (progn (cancel-timer timer))))))))) (if (eq 'error (car retval)) (progn (signal 'jsonrpc-error (cons (format "request id=%s failed:" (car id-and-timer)) (cdr retval))))) (car (cdr retval))))
  (let* ((deferred (car (cdr (plist-member --cl-rest-- ':deferred)))) (timeout (car (cdr (plist-member --cl-rest-- ':timeout)))) (cancel-on-input (car (cdr (plist-member --cl-rest-- ':cancel-on-input)))) (cancel-on-input-retval (car (cdr (plist-member --cl-rest-- ':cancel-on-input-retval))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:deferred :timeout :cancel-on-input :cancel-on-input-retval :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:deferred :timeout :cancel-on-input :cancel-on-input-retval)" (car --cl-keys--)))))) (let* ((tag (cl-gensym "jsonrpc-request-catch-tag")) id-and-timer cancelled (retval (unwind-protect (catch tag (setq id-and-timer (jsonrpc--async-request-1 connection method params :success-fn (function (lambda (result) (if cancelled nil (throw tag (list 'done result))))) :error-fn (function (lambda (jsonrpc-lambda-elem71) (apply (function (lambda (&rest --cl-rest--) "\n\n(fn &key CODE MESSAGE DATA)" (let* ((code (car (cdr (plist-member --cl-rest-- ':code)))) (message (car (cdr (plist-member --cl-rest-- ':message)))) (data (car (cdr (plist-member --cl-rest-- ':data))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:code :message :data :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:code :message :data)" (car --cl-keys--)))))) (if cancelled nil (throw tag (list 'error (cons 'jsonrpc-error-code code) (cons 'jsonrpc-error-message message) (cons 'jsonrpc-error-data data)))))))) jsonrpc-lambda-elem71))) :timeout-fn (function (lambda nil (if cancelled nil (throw tag '(error (jsonrpc-error-message . "Timed out")))))) :deferred deferred :timeout timeout)) (cond (cancel-on-input (while (sit-for 30)) (setq cancelled t) (list 'cancelled cancel-on-input-retval)) (t (while t (accept-process-output nil 30))))) (let* ((x225 (car id-and-timer)) (x226 (cdr id-and-timer)) (x227 (car x226)) (x228 (cdr x226))) (let ((timer x227) (id x225)) (progn (remhash id (jsonrpc--request-continuations connection)) (remhash (list deferred (current-buffer)) (jsonrpc--deferred-actions connection)) (if timer (progn (cancel-timer timer))))))))) (if (eq 'error (car retval)) (progn (signal 'jsonrpc-error (cons (format "request id=%s failed:" (car id-and-timer)) (cdr retval))))) (car (cdr retval)))))
  (closure (t) (connection method params &rest --cl-rest--) "Make a request to CONNECTION, wait for a reply.\nLike `jsonrpc-async-request' for CONNECTION, METHOD and PARAMS,\nbut synchronous.\n\nExcept in the case of a non-nil CANCEL-ON-INPUT (explained\nbelow), this function doesn't exit until anything interesting\nhappens (success reply, error reply, or timeout).  Furthermore,\nit only exits locally (returning the JSONRPC result object) if\nthe request is successful, otherwise it exits non-locally with an\nerror of type `jsonrpc-error'.\n\nDEFERRED is passed to `jsonrpc-async-request', which see.\n\nIf CANCEL-ON-INPUT is non-nil and the user inputs something while\nthe functino is waiting, then it exits immediately, returning\nCANCEL-ON-INPUT-RETVAL.  Any future replies (normal or error) are\nignored.\n\n(fn CONNECTION METHOD PARAMS &key DEFERRED TIMEOUT CANCEL-ON-INPUT CANCEL-ON-INPUT-RETVAL)" (let* ((deferred (car (cdr (plist-member --cl-rest-- ':deferred)))) (timeout (car (cdr (plist-member --cl-rest-- ':timeout)))) (cancel-on-input (car (cdr (plist-member --cl-rest-- ':cancel-on-input)))) (cancel-on-input-retval (car (cdr (plist-member --cl-rest-- ':cancel-on-input-retval))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:deferred :timeout :cancel-on-input :cancel-on-input-retval :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:deferred :timeout :cancel-on-input :cancel-on-input-retval)" (car --cl-keys--)))))) (let* ((tag (cl-gensym "jsonrpc-request-catch-tag")) id-and-timer cancelled (retval (unwind-protect (catch tag (setq id-and-timer (jsonrpc--async-request-1 connection method params :success-fn (function (lambda (result) (if cancelled nil (throw tag (list 'done result))))) :error-fn (function (lambda (jsonrpc-lambda-elem71) (apply (function (lambda (&rest --cl-rest--) "\n\n(fn &key CODE MESSAGE DATA)" (let* ((code (car (cdr (plist-member --cl-rest-- ':code)))) (message (car (cdr (plist-member --cl-rest-- ':message)))) (data (car (cdr (plist-member --cl-rest-- ':data))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:code :message :data :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:code :message :data)" (car --cl-keys--)))))) (if cancelled nil (throw tag (list 'error (cons 'jsonrpc-error-code code) (cons 'jsonrpc-error-message message) (cons 'jsonrpc-error-data data)))))))) jsonrpc-lambda-elem71))) :timeout-fn (function (lambda nil (if cancelled nil (throw tag '(error (jsonrpc-error-message . "Timed out")))))) :deferred deferred :timeout timeout)) (cond (cancel-on-input (while (sit-for 30)) (setq cancelled t) (list 'cancelled cancel-on-input-retval)) (t (while t (accept-process-output nil 30))))) (let* ((x225 (car id-and-timer)) (x226 (cdr id-and-timer)) (x227 (car x226)) (x228 (cdr x226))) (let ((timer x227) (id x225)) (progn (remhash id (jsonrpc--request-continuations connection)) (remhash (list deferred (current-buffer)) (jsonrpc--deferred-actions connection)) (if timer (progn (cancel-timer timer))))))))) (if (eq 'error (car retval)) (progn (signal 'jsonrpc-error (cons (format "request id=%s failed:" (car id-and-timer)) (cdr retval))))) (car (cdr retval))))))(#<eglot-eclipse-jdt eglot-eclipse-jdt> :textDocument/rename (:textDocument (:uri "file:///home/j3kyl/a.java") :position (:line 5 :character 7) :newName "."))
  apply((closure (t) (connection method params &rest --cl-rest--) "Make a request to CONNECTION, wait for a reply.\nLike `jsonrpc-async-request' for CONNECTION, METHOD and PARAMS,\nbut synchronous.\n\nExcept in the case of a non-nil CANCEL-ON-INPUT (explained\nbelow), this function doesn't exit until anything interesting\nhappens (success reply, error reply, or timeout).  Furthermore,\nit only exits locally (returning the JSONRPC result object) if\nthe request is successful, otherwise it exits non-locally with an\nerror of type `jsonrpc-error'.\n\nDEFERRED is passed to `jsonrpc-async-request', which see.\n\nIf CANCEL-ON-INPUT is non-nil and the user inputs something while\nthe functino is waiting, then it exits immediately, returning\nCANCEL-ON-INPUT-RETVAL.  Any future replies (normal or error) are\nignored.\n\n(fn CONNECTION METHOD PARAMS &key DEFERRED TIMEOUT CANCEL-ON-INPUT CANCEL-ON-INPUT-RETVAL)" (let* ((deferred (car (cdr (plist-member --cl-rest-- ':deferred)))) (timeout (car (cdr (plist-member --cl-rest-- ':timeout)))) (cancel-on-input (car (cdr (plist-member --cl-rest-- ':cancel-on-input)))) (cancel-on-input-retval (car (cdr (plist-member --cl-rest-- ':cancel-on-input-retval))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:deferred :timeout :cancel-on-input :cancel-on-input-retval :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:deferred :timeout :cancel-on-input :cancel-on-input-retval)" (car --cl-keys--)))))) (let* ((tag (cl-gensym "jsonrpc-request-catch-tag")) id-and-timer cancelled (retval (unwind-protect (catch tag (setq id-and-timer (jsonrpc--async-request-1 connection method params :success-fn (function (lambda (result) (if cancelled nil (throw tag (list 'done result))))) :error-fn (function (lambda (jsonrpc-lambda-elem71) (apply (function (lambda (&rest --cl-rest--) "\n\n(fn &key CODE MESSAGE DATA)" (let* ((code (car (cdr (plist-member --cl-rest-- ':code)))) (message (car (cdr (plist-member --cl-rest-- ':message)))) (data (car (cdr (plist-member --cl-rest-- ':data))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:code :message :data :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:code :message :data)" (car --cl-keys--)))))) (if cancelled nil (throw tag (list 'error (cons 'jsonrpc-error-code code) (cons 'jsonrpc-error-message message) (cons 'jsonrpc-error-data data)))))))) jsonrpc-lambda-elem71))) :timeout-fn (function (lambda nil (if cancelled nil (throw tag '(error (jsonrpc-error-message . "Timed out")))))) :deferred deferred :timeout timeout)) (cond (cancel-on-input (while (sit-for 30)) (setq cancelled t) (list 'cancelled cancel-on-input-retval)) (t (while t (accept-process-output nil 30))))) (let* ((x225 (car id-and-timer)) (x226 (cdr id-and-timer)) (x227 (car x226)) (x228 (cdr x226))) (let ((timer x227) (id x225)) (progn (remhash id (jsonrpc--request-continuations connection)) (remhash (list deferred (current-buffer)) (jsonrpc--deferred-actions connection)) (if timer (progn (cancel-timer timer))))))))) (if (eq 'error (car retval)) (progn (signal 'jsonrpc-error (cons (format "request id=%s failed:" (car id-and-timer)) (cdr retval))))) (car (cdr retval)))))) (#<eglot-eclipse-jdt eglot-eclipse-jdt> :textDocument/rename (:textDocument (:uri "file:///home/j3kyl/a.java") :position (:line 5 :character 7) :newName ".")))
  jsonrpc-request(#<eglot-eclipse-jdt eglot-eclipse-jdt> :textDocument/rename (:textDocument (:uri "file:///home/j3kyl/a.java") :position (:line 5 :character 7) :newName "."))
  eglot-rename(".")
  funcall-interactively(eglot-rename ".")
  #<subr call-interactively>(eglot-rename record nil)
  apply(#<subr call-interactively> eglot-rename (record nil))
  (let ((ido-cr+-current-command command)) (apply orig-fun command args))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> eglot-rename record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (eglot-rename record nil))
  call-interactively(eglot-rename record nil)
  command-execute(eglot-rename record)
  execute-extended-command(nil "eglot-rename" "egloren")
  funcall-interactively(execute-extended-command nil "eglot-rename" "egloren")
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> execute-extended-command (nil nil))
  (let ((ido-cr+-current-command command)) (apply orig-fun command args))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> execute-extended-command nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Server: jdt-language-server-0.30.0-201812072141.tar.gz
Eglot version: 1.2
Debian SID
T430

**Comment by mkcms** [comment]
I don't think it's an issue in Eglot or the language server. You're trying to rename a symbol to something which is not a valid symbol in Java ("."), so the server simply refuses to do that. Eglot errors out because the server errors out. If you rename to a normal identifier, like `foobar`, doesn't it work?

**Comment by mkcms** [comment]
@eubarbosa 
Can you apply this patch to Eglot repo and try again?

```diff
diff --git a/eglot.el b/eglot.el
index f442b2f..65633f7 100644
--- a/eglot.el
+++ b/eglot.el
@@ -447,7 +447,9 @@ treated as in `eglot-dbind'."
             :workspace (list
                         :applyEdit t
                         :executeCommand `(:dynamicRegistration :json-false)
-                        :workspaceEdit `(:documentChanges :json-false)
+                        :workspaceEdit (list :documentChanges :json-false
+                                             :resourceOperations []
+                                             :failureHanlding [])
                         :didChangeWatchedFiles `(:dynamicRegistration t)
                         :symbol `(:dynamicRegistration :json-false))
```

**Comment by eubarbosa** [comment]
@mkcms 

1. Your patch issues a error as Eglot loads: 
`error in process filter: progn: Wrong number of arguments: (5 . 5), 6`
2. It correctly rename all occurence of z and issues: RENAME SUCCESSFUL

**Comment by mkcms** [comment]
>     1. It correctly rename all occurence of z and issues: RENAME SUCCESSFUL

Right. There's a bug in the server. If we don't provide `resourceOperations` and `failureHandling` keys in initialization options, the server errors out with:

```
jsonrpc-error: "request id=2 failed:", (jsonrpc-error-code . -32603), (jsonrpc-error-message . "Internal error."), (jsonrpc-error-data . "java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.jdt.ls.core.internal.preferences.ClientPreferences.isResourceOperationSupported(ClientPreferences.java:185)
	at org.eclipse.jdt.ls.core.internal.ChangeUtil.convertTextEdit(ChangeUtil.java:220)
	at org.eclipse.jdt.ls.core.internal.ChangeUtil.convertTextChange(ChangeUtil.java:209)
	at org.eclipse.jdt.ls.core.internal.ChangeUtil.doConvertCompositeChange(ChangeUtil.java:132)
	at org.eclipse.jdt.ls.core.internal.ChangeUtil.convertCompositeChange(ChangeUtil.java:90)
	at org.eclipse.jdt.ls.core.internal.handlers.RenameHandler.rename(RenameHandler.java:95)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$21(JDTLanguageServer.java:666)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
")
```

We should report that to the eclipse.jdt repo. We can also use the workaround I posted above.

---

>     2\. Your patch issues a error as Eglot loads:
>         `error in process filter: progn: Wrong number of arguments: (5 . 5), 6`

That doesn't look like an error caused by Eglot, but by the legacy Flymake backend. @joaotavora Can probably help you with that.
I think you can do this

```elisp
(setq-default flymake-diagnostic-functions nil)
```

to disable that error (then `M-x eglot` again).

**Comment by eubarbosa** [comment]
@mkcms 
1. Are you up to report that bug? I dont know nothing about lsp and eclipse-jtd-ls. Anyway, I can try or ask for anyone up to it! :1st_place_medal: 
2. Flymake-legacy, that is weird, I just require flymake I have not tweaked it.

**Comment by mkcms** [comment]
>     1. I know nothing about lsp and eclipse-jtd-ls but I can give it a shot!

You can report the bug at https://github.com/eclipse/eclipse.jdt.ls.
