### ISSUE TITLE
Flymake only checks when the buffer is saved for Elixir

### ISSUE THREAD

**Issue by xuchunyang** [joaotavora/eglot#208]
I added Elixir support via https://github.com/elixir-lsp/elixir-ls, and here is my config

```elisp
(add-to-list
 'eglot-server-programs
 '(elixir-mode "~/src/elixir-ls/release/language_server.sh"))
```

and I don't have any other config on Eglot and Flymake.

I notice Flymake doesn't update unless I save the buffer to disk, inserting newline doesn't help. However, Flymake does check on-the-fly in Emacs Lisp buffers.

---

eglot 20190106.2214
flymake 1.0.3
elixir-ls Latest commit 030a987
emacs 26.1

**Comment by joaotavora** [comment]
This might be related to the exilir server.  Perhaps it only sends diagnostics on save. Can you show the contents of the *events* buffer?  You can use `M-x eglot-events-buffer` or click the eglot indicator in the mode-line.

**Comment by xuchunyang** [comment]
`M-x eglot` in buffer with the following initial contents, then change the wrong `1 + "2"` to the right `1 + 2`

```
defmodule Ls.CLI do
  def main(_args) do
    1 + "2"
  end
end

```

the events buffer:

```
client-request (id:1) Tue Jan 15 00:45:41 2019:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 56570 :rootPath "/Users/xcy/learn-elixir/ls/" :rootUri "file:///Users/xcy/learn-elixir/ls/" :initializationOptions nil :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false))
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false)
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental nil)))

server-notification Tue Jan 15 00:45:42 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Started ElixirLS" :type 4))

server-notification Tue Jan 15 00:45:42 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Elixir version: \"1.7.4 (compiled with Erlang/OTP 21)\"" :type 4))

server-notification Tue Jan 15 00:45:42 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Erlang version: \"21\"" :type 4))

server-reply (id:1) Tue Jan 15 00:45:42 2019:
(:id 1 :jsonrpc "2.0" :result
     (:capabilities
      (:codeLensProvider
       (:resolveProvider :json-false)
       :completionProvider
       (:triggerCharacters
        ["." "@"])
       :definitionProvider t :documentFormattingProvider t :documentOnTypeFormattingProvider
       (:firstTriggerCharacter "\n")
       :documentSymbolProvider t :executeCommandProvider
       (:commands
        ["spec"])
       :hoverProvider t :macroExpansion t :referencesProvider t :signatureHelpProvider
       (:triggerCharacters
        ["("])
       :textDocumentSync 2)))

client-notification Tue Jan 15 00:45:42 2019:
(:jsonrpc "2.0" :method "initialized" :params
          (:__dummy__ t))

client-notification Tue Jan 15 00:45:42 2019:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex" :version 0 :languageId "elixir" :text "defmodule Ls do\n  @moduledoc \"\"\"\n  Documentation for Ls.\n  \"\"\"\n\n  @doc \"\"\"\n  Hello world.\n\n  ## Examples\n\n      iex> Ls.hello()\n      :world\n\n  \"\"\"\n  def hello do\n    :world\n  end\nend\n\ndefmodule Ls.CLI do\n  def main(_args) do\n    1 + \"2\"\n  end\nend\n")))

client-notification Tue Jan 15 00:45:42 2019:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings nil))

server-notification Tue Jan 15 00:45:42 2019:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           []
           :uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex"))

server-notification Tue Jan 15 00:45:47 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "\n00:45:47.173 [warn]  Did not receive workspace/didChangeConfiguration notification after 5 seconds. Using default settings." :type 4))

server-notification Tue Jan 15 00:45:48 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Compiling with Mix env test" :type 4))

server-notification Tue Jan 15 00:45:48 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Analyzing 0 modules: []" :type 3))

server-notification Tue Jan 15 00:45:48 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Analysis finished in 46 milliseconds" :type 3))

server-notification Tue Jan 15 00:45:48 2019:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           [(:message "Function main/1 has no local return." :range
                      (:end
                       (:character 20 :line 20)
                       :start
                       (:character 2 :line 20))
                      :severity 2 :source "Dialyzer")
            (:message "The function call will fail." :range
                      (:end
                       (:character 11 :line 21)
                       :start
                       (:character 4 :line 21))
                      :severity 2 :source "Dialyzer")]
           :uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex"))

server-notification Tue Jan 15 00:45:48 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Compiling 1 file (.ex)" :type 4))

server-notification Tue Jan 15 00:45:48 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "warning: this expression will fail with ArithmeticError\n  lib/ls.ex:22\n" :type 2))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Compile took 750 milliseconds" :type 3))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Checking for stale beam files" :type 3))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           [(:message "Function main/1 has no local return." :range
                      (:end
                       (:character 20 :line 20)
                       :start
                       (:character 2 :line 20))
                      :severity 2 :source "Dialyzer")
            (:message "this expression will fail with ArithmeticError" :range
                      (:end
                       (:character 11 :line 21)
                       :start
                       (:character 4 :line 21))
                      :severity 2 :source "Elixir")
            (:message "The function call will fail." :range
                      (:end
                       (:character 11 :line 21)
                       :start
                       (:character 4 :line 21))
                      :severity 2 :source "Dialyzer")]
           :uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex"))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Analyzing 0 modules: []" :type 3))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Analysis finished in 12 milliseconds" :type 3))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           [(:message "Function main/1 has no local return." :range
                      (:end
                       (:character 20 :line 20)
                       :start
                       (:character 2 :line 20))
                      :severity 2 :source "Dialyzer")
            (:message "this expression will fail with ArithmeticError" :range
                      (:end
                       (:character 11 :line 21)
                       :start
                       (:character 4 :line 21))
                      :severity 2 :source "Elixir")
            (:message "The function call will fail." :range
                      (:end
                       (:character 11 :line 21)
                       :start
                       (:character 4 :line 21))
                      :severity 2 :source "Dialyzer")]
           :uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex"))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Dialyzer analysis is up to date" :type 3))

server-notification Tue Jan 15 00:45:49 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Writing manifest..." :type 3))

server-notification Tue Jan 15 00:45:52 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Done writing manifest." :type 3))

client-notification Tue Jan 15 00:45:57 2019:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex" :version 2)
           :contentChanges
           [(:range
             (:start
              (:line 21 :character 8)
              :end
              (:line 21 :character 11))
             :rangeLength 3 :text "")
            (:range
             (:start
              (:line 21 :character 8)
              :end
              (:line 21 :character 8))
             :rangeLength 0 :text "2")]))

client-request (id:2) Tue Jan 15 00:45:57 2019:
(:jsonrpc "2.0" :id 2 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex")
           :position
           (:line 21 :character 4)))

client-request (id:3) Tue Jan 15 00:45:57 2019:
(:jsonrpc "2.0" :id 3 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex")
           :position
           (:line 21 :character 4)))

server-reply (id:2) Tue Jan 15 00:45:57 2019:
(:id 2 :jsonrpc "2.0" :result
     (:signatures
      []))

server-reply (id:3) Tue Jan 15 00:45:57 2019:
(:id 3 :jsonrpc "2.0" :result
     (:contents
      []
      :range
      (:end
       (:character 5 :line 21)
       :start
       (:character 4 :line 21))))

```

When I save the buffer, Flymake updates, and here is the appended content in the events buffer

```
client-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "textDocument/willSave" :params
          (:reason 1 :textDocument
                   (:uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex")))

client-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "textDocument/didSave" :params
          (:text "defmodule Ls do\n  @moduledoc \"\"\"\n  Documentation for Ls.\n  \"\"\"\n\n  @doc \"\"\"\n  Hello world.\n\n  ## Examples\n\n      iex> Ls.hello()\n      :world\n\n  \"\"\"\n  def hello do\n    :world\n  end\nend\n\ndefmodule Ls.CLI do\n  def main(_args) do\n    1 + 2\n  end\nend\n" :textDocument
                 (:uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex")))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "warning: Received unmatched notification: %{\"jsonrpc\" => \"2.0\", \"method\" => \"textDocument/willSave\", \"params\" => %{\"reason\" => 1, \"textDocument\" => %{\"uri\" => \"file:///Users/xcy/learn-elixir/ls/lib/ls.ex\"}}}\n  (language_server) lib/language_server/server.ex:291: ElixirLS.LanguageServer.Server.handle_notification/2\n  (language_server) lib/language_server/server.ex:145: ElixirLS.LanguageServer.Server.handle_cast/2\n  (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4\n  (stdlib) gen_server.erl:711: :gen_server.handle_msg/6\n  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n" :type 2))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Compiling with Mix env test" :type 4))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Compiling 1 file (.ex)" :type 4))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Compile took 195 milliseconds" :type 3))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Checking for stale beam files" :type 3))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           [(:message "Function main/1 has no local return." :range
                      (:end
                       (:character 20 :line 20)
                       :start
                       (:character 2 :line 20))
                      :severity 2 :source "Dialyzer")
            (:message "The function call will fail." :range
                      (:end
                       (:character 9 :line 21)
                       :start
                       (:character 4 :line 21))
                      :severity 2 :source "Dialyzer")]
           :uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex"))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Analyzing 1 modules: [Ls.CLI]" :type 3))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Analysis finished in 387 milliseconds" :type 3))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           []
           :uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex"))

server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "Dialyzer analysis is up to date" :type 3))

server-notification Tue Jan 15 00:50:30 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Writing manifest..." :type 3))

server-notification Tue Jan 15 00:50:32 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:message "[ElixirLS Dialyzer] Done writing manifest." :type 3))
```

**Comment by xuchunyang** [comment]
Not matter how I change the buffer, the publishDiagnostics event doesn't arrive

```
server-notification Tue Jan 15 00:50:29 2019:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           []
           :uri "file:///Users/xcy/learn-elixir/ls/lib/ls.ex"))
```

but Isn't it Flymake/Eglot's job to tell the elixir server to recheck the buffer? I have zero knowledge of LSP.

**Comment by xuchunyang** [comment]
By the way, there is "Wait" in Flymake's mode line lighter, and it disappears only when I save the buffer

![screen shot 2019-01-15 at 1 12 44 am](https://user-images.githubusercontent.com/4550353/51128393-b25fdf80-1862-11e9-8128-65d5e969d487.png)

**Comment by joaotavora** [comment]
> but Isn't it Flymake/Eglot's job to tell the elixir server to recheck the buffer? I have zero knowledge of LSP.

It's Eglot's job to say that the buffer has changed.  It's Elixir server's job to decide if that's a good time to publish new diagnostics.  It isn't doing that.  Perhaps it doesn't support incremental buffer change notifications (yet).

Closing this.

> By the way, there is "Wait" in Flymake's mode line lighter, and it disappears only when I save the buffer

This is normal, Flymake is waiting for new diagnostics to arrive after having notified the server of buffer changes, but they never arrive (only when you save).
