### ISSUE TITLE
"Import build" from scala metals not working

### ISSUE THREAD

**Issue by Crandel** [joaotavora/eglot#362]
When I opened a scala file from new project eglot asks me to import build. I do it and wait for some time, but nothing happened, go-to definition is not working and any of metals features too. But when I opened same file from visual studio code and import build there, it shows me build progress and after finishing all metals features works in emacs eglot too.

**Comment by joaotavora** [comment]
>  eglot asks me to import build

? I don't remember eglot asking any such questions....

Can you post a reproducible recipe? What exactly are you doing?

**Comment by Crandel** [comment]
I'm an Arch Linux user. So I installed latest scala-metals package from [AUR](https://aur.archlinux.org/packages/metals/), and [configured](https://github.com/Crandel/home/blob/master/.emacs.d/settings/recipes/eglot.rcp#L10) eglot to use metals as backend.
I use [this project](https://github.com/Crandel/akka_webchat).
This is a dialog with question
![](https://habrastorage.org/webt/nu/43/lq/nu43lqo2ukbo-xv6b9lih_jwiq0.png)
And here is [output](https://pastebin.com/Q52XwVq0) of `*EGLOT (akka-webchat/scala-mode) events*` buffer

**Comment by joaotavora** [comment]
Oh! it's a question asked by Eglot _on behalf_ of the server.  I had forgotten i had implemented those LSP things... (and indeed didn't know they worked).

Well I guess they don't... :-)

I don't have an easy way to test this, short from installing `scala-metals` myself, but I'll have a look at the output you posted, maybe that'll provide a hint as to what is going on.

**Comment by Crandel** [comment]
Thank you very much!

**Comment by joaotavora** [comment]
Can you try with this latest commit? I had a look and Eglot wasn't following the spec correctly on this one, although the spec looks quite crummy in this regard anyway, according to its maintainer also. https://github.com/Microsoft/language-server-protocol/issues/230

**Comment by Crandel** [comment]
I updated eglot to latest master and I got this error
```
(:jsonrpc "2.0" :id "2" :method "window/showMessageRequest" :params
          (:actions
           [(:title "Import build")
            (:title "Not now")
            (:title "Don't show again")]
           :type 3 :message "New sbt workspace detected, would you like to import the build?"))

server-notification Sat Nov 30 12:28:10 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "no build target: /home/crandel/projects/scala/akka-webchat/build.sbt"))

client-reply (id:2) Sat Nov 30 12:28:11 2019:
(:jsonrpc "2.0" :id "2" :result "Import build" :error nil)

server-notification Sat Nov 30 12:28:11 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "Unexpected error initializing server\norg.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.\n	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)\n	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)\n	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)\n	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n	at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n	at java.lang.Thread.run(Thread.java:748)\n"))

```

**Comment by joaotavora** [comment]
Hi.  I asked you up update eglot to that commit I mentioned, which I won't push to master until you try it out.  Can you do that?

**Comment by Crandel** [comment]
Oh, sorry, my fault. I used your commit and now it`s works
```
server-request (id:2) Sat Nov 30 14:22:52 2019:
(:jsonrpc "2.0" :id "2" :method "window/showMessageRequest" :params
          (:actions
           [(:title "Import build")
            (:title "Not now")
            (:title "Don't show again")]
           :type 3 :message "New sbt workspace detected, would you like to import the build?"))

server-notification Sat Nov 30 14:22:52 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "no build target: /home/crandel/projects/scala/akka-webchat/build.sbt"))

client-reply (id:2) Sat Nov 30 14:22:53 2019:
(:jsonrpc "2.0" :id "2" :result
          (:title "Import build")
          :error nil)

server-notification Sat Nov 30 14:22:53 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "running '/usr/lib/jvm/java-8-openjdk/jre/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals8147492027721677651/sbt-launch.jar metalsEnable bloopInstall'"))

server-notification Sat Nov 30 14:22:57 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "[info] Loading settings for project global-plugins from build.sbt,metals.sbt ..."))

server-notification Sat Nov 30 14:22:58 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "[info] Loading global plugins from /home/crandel/.sbt/1.0/plugins"))

server-notification Sat Nov 30 14:22:59 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "[info] Updating ProjectRef(uri(\"file:/home/crandel/.sbt/1.0/plugins/\"), \"global-plugins\")..."))

server-notification Sat Nov 30 14:23:01 2019:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "[info] Done updating."))

```
