### ISSUE TITLE
TypeScript server crashes when project requires Nodejs 16

### ISSUE THREAD

**Issue by angrybacon** [joaotavora/eglot#795]
* Server used: `typescript-language-server`
* Emacs version: `GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.6 (Build 20G165)) of 2021-11-08`
* Operating system: macOS
* Eglot version: `dade5a148712463a15b7ac65f779e25596a3eefc`
* Eglot installation method: `straight`
* Using Doom: No

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)

<details>
<summary>M-x eglot-events-buffer</summary>

```lisp
[client-request] (id:1) Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 50402 :rootPath "/Users/angrybacon/Workspace/projectname/" :rootUri "file:///Users/angrybacon/Workspace/projectname" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                                                      ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport t)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false))
                       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))))
[server-reply] (id:1) Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync 2 :completionProvider
                              (:triggerCharacters
                               ["." "\"" "'" "/" "@" "<"]
                               :resolveProvider t)
                              :codeActionProvider t :definitionProvider t :documentFormattingProvider t :documentHighlightProvider t :documentSymbolProvider t :executeCommandProvider
                              (:commands
                               ["_typescript.applyWorkspaceEdit" "_typescript.applyCodeAction" "_typescript.applyRefactoring" "_typescript.organizeImports" "_typescript.applyRenameFile"])
                              :hoverProvider t :renameProvider t :referencesProvider t :signatureHelpProvider
                              (:triggerCharacters
                               ["(" "," "<"])
                              :workspaceSymbolProvider t :implementationProvider t :typeDefinitionProvider t :foldingRangeProvider t :callsProvider t)))
[client-notification] Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                            ()))
[client-notification] Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx" :version 0 :languageId "typescript-tsx" :text "")))
[client-notification] Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings nil))
[client-request] (id:2) Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :id 2 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")
           :position
           (:line 0 :character 0)))
[client-request] (id:3) Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :id 3 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")
           :position
           (:line 0 :character 0)))
[client-request] (id:4) Wed Jan 12 18:20:13 2022:
(:jsonrpc "2.0" :id 4 :method "textDocument/documentHighlight" :params
          (:textDocument
           (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")
           :position
           (:line 0 :character 0)))
[client-notification] Wed Jan 12 18:20:14 2022:
(:jsonrpc "2.0" :method "textDocument/willSave" :params
          (:reason 1 :textDocument
                   (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")))
[client-notification] Wed Jan 12 18:20:14 2022:
(:jsonrpc "2.0" :method "textDocument/didSave" :params
          (:text "" :textDocument
                 (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")))
[internal] (id:2) Wed Jan 12 18:20:23 2022:
(:timed-out :textDocument/signatureHelp :id 2 :params
            (:textDocument
             (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")
             :position
             (:line 0 :character 0)))
[internal] (id:3) Wed Jan 12 18:20:23 2022:
(:timed-out :textDocument/hover :id 3 :params
            (:textDocument
             (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")
             :position
             (:line 0 :character 0)))
[internal] (id:4) Wed Jan 12 18:20:23 2022:
(:timed-out :textDocument/documentHighlight :id 4 :params
            (:textDocument
             (:uri "file:///Users/angrybacon/Workspace/projectname/index.tsx")
             :position
             (:line 0 :character 0)))
[server-reply] (id:2) Wed Jan 12 18:20:33 2022:
(:jsonrpc "2.0" :id 2 :result nil)
[server-reply] (id:3) Wed Jan 12 18:20:33 2022:
(:jsonrpc "2.0" :id 3 :result
          (:contents
           []))
[server-reply] (id:4) Wed Jan 12 18:20:33 2022:
(:jsonrpc "2.0" :id 4 :result
          [])
[stderr] /usr/local/lib/node_modules/typescript-language-server/lib/utils.js:24
[stderr]             this.reject(new Error(this.operation + " timeout"));
[stderr]                         ^
[stderr] 
[stderr] Error: geterr timeout
[stderr]     at Timeout.<anonymous> (/usr/local/lib/node_modules/typescript-language-server/lib/utils.js:24:25)
[stderr]     at listOnTimeout (node:internal/timers:557:17)
[stderr]     at processTimers (node:internal/timers:500:7)
[internal] Wed Jan 12 18:20:33 2022:
(:message "Connection state changed" :change "exited abnormally with code 1\n")

----------b---y---e---b---y---e----------
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process EGLOT (projectname/typescript-tsx-mode) stderr finished
[client-request] (id:1) Wed Jan 12 18:20:33 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 50402 :rootPath "/Users/angrybacon/Workspace/projectname/" :rootUri "file:///Users/angrybacon/Workspace/projectname" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                                                      ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport t)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false))
                       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))))
[server-reply] (id:1) Wed Jan 12 18:20:33 2022:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync 2 :completionProvider
                              (:triggerCharacters
                               ["." "\"" "'" "/" "@" "<"]
                               :resolveProvider t)
                              :codeActionProvider t :definitionProvider t :documentFormattingProvider t :documentHighlightProvider t :documentSymbolProvider t :executeCommandProvider
                              (:commands
                               ["_typescript.applyWorkspaceEdit" "_typescript.applyCodeAction" "_typescript.applyRefactoring" "_typescript.organizeImports" "_typescript.applyRenameFile"])
                              :hoverProvider t :renameProvider t :referencesProvider t :signatureHelpProvider
                              (:triggerCharacters
                               ["(" "," "<"])
                              :workspaceSymbolProvider t :implementationProvider t :typeDefinitionProvider t :foldingRangeProvider t :callsProvider t)))
[client-notification] Wed Jan 12 18:20:33 2022:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                            ()))
```
</details>
    
#### Backtrace (mandatory, unless no error message seen or heard):

<details>
<summary>M-x toggle-debug-on-error</summary>

```lisp
Debugger entered--Lisp error: (error "Process EGLOT (projectname/typescript-tsx-mode) not ...")
  process-send-string(#<process EGLOT (projectname/typescript-tsx-mode)> "Content-Length: 146\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"...")
  #f(compiled-function (arg1 &rest rest) "Send MESSAGE, a JSON object, to CONNECTION." #<bytecode -0x14a03cc39ebbf048>)(#<eglot-lsp-server eglot-lsp-server-1fe134bfd584> :method :textDocument/didClose :params (:textDocument (:uri "file:///Users/angrybacon/Workspace/projectname/...")))
  apply(#f(compiled-function (arg1 &rest rest) "Send MESSAGE, a JSON object, to CONNECTION." #<bytecode -0x14a03cc39ebbf048>) #<eglot-lsp-server eglot-lsp-server-1fe134bfd584> (:method :textDocument/didClose :params (:textDocument (:uri "file:///Users/angrybacon/Workspace/projectname/..."))))
  jsonrpc-connection-send(#<eglot-lsp-server eglot-lsp-server-1fe134bfd584> :method :textDocument/didClose :params (:textDocument (:uri "file:///Users/angrybacon/Workspace/projectname/...")))
  jsonrpc-notify(#<eglot-lsp-server eglot-lsp-server-1fe134bfd584> :textDocument/didClose (:textDocument (:uri "file:///Users/angrybacon/Workspace/projectname/...")))
  eglot--signal-textDocument/didClose()
  run-hooks(before-revert-hook)
  revert-buffer--default(nil t)
  revert-buffer(nil t)
  (lambda nil (interactive) (revert-buffer nil t))()
  funcall-interactively((lambda nil (interactive) (revert-buffer nil t)))
  command-execute((lambda nil (interactive) (revert-buffer nil t)))
```
</details>
   
#### Minimal configuration (mandatory)

1. Have no *system* Nodejs installed
1. Pick Nodejs 16 with `nvm alias default 16`
1. Start Emacs
1. Confirm the version with `M-! node -v RET`
1. Specify the Nodejs version in the root `package.json` file ie. `"engines": {"node": "^16"}`
1. Open a buffer to any `index.ts` file and enable `eglot`
 
 

#### What Worked

I initially discovered the issue when my project started using `"engines": {"node": "^16"}` in the `package.json` file. At the time I had Nodejs installed globally on my system (latest version: 17) and had no issue. Since then I removed the global Nodejs and started using `nvm` instead. Here is what I tried

❌ With `"engines": {"node": "^16"}` in the `package.json` + `M-! node -v RET` -> 16 (this is what should work)
❌ With `"engines": {"node": "^16"}` in the `package.json` + `M-! node -v RET` -> 17
❌ With `"engines": {"node": "^17"}` in the `package.json` + `M-! node -v RET` -> 16
✔️ With `"engines": {"node": "^17"}` in the `package.json` + `M-! node -v RET` -> 17

Let me know what other debugging details I can provide

**Comment by skangas** [comment]
This looks like a bug in the language server, right?
```
[stderr] /usr/local/lib/node_modules/typescript-language-server/lib/utils.js:24
[stderr]             this.reject(new Error(this.operation + " timeout"));
[stderr]                         ^
[stderr] 
[stderr] Error: geterr timeout
[stderr]     at Timeout.<anonymous> (/usr/local/lib/node_modules/typescript-language-server/lib/utils.js:24:25)
[stderr]     at listOnTimeout (node:internal/timers:557:17)
[stderr]     at processTimers (node:internal/timers:500:7)
```
However, we could perhaps be more graceful when the server crashes. I'm not sure exactly what we should do, though.

Any ideas? Just signal an error, or prompt to restart the server?

**Comment by joaotavora** [comment]
@skangas I'd say we are already as graceful as we can: we auto-restart suddently crashing servers a number of times until the restarts start piling up and we're doing too many of them.  There's a variable for controling the auto-restart behaviour, forgot the name.

@angrybacon when switching between major node versions, some Node packages require native extensions to be re-compiled.  So you may need to either `npm install typescript-language-server`, or `npm install -g typescript-language-server`, or delete the `node_modules` or any combination of these.  Of course only do this when changing the global node version.

**Comment by angrybacon** [comment]
This may be related to a recent `npm rebuild` I had to run 🤔 Thanks for the details, I'll test that out

**Comment by joaotavora** [comment]
Yeah, maybe `npm rebuild` is a more efficient, correct way to do more or less what I suggested above.

**Comment by skangas** [comment]
> @skangas I'd say we are already as graceful as we can: we auto-restart suddently crashing servers a number of times until the restarts start piling up and we're doing too many of them. There's a variable for controling the auto-restart behaviour, forgot the name.

That's fair enough. Perhaps you mean `eglot-autoreconnect`?

As you can tell, I'm learning on the job here. ;-)

**Comment by skangas** [comment]
> This may be related to a recent `npm rebuild` I had to run thinking Thanks for the details, I'll test that out

Please let us know what you find out, in case anyone else stumbles upon this. I've added the tags `server-bug` and `workaround` in the hope that @joaotavora's suggestions helped, and I'm closing this issue. Thanks!

**Comment by joaotavora** [comment]
> As you can tell, I'm learning on the job here. ;-)

doing just fine ;-)

**Comment by angrybacon** [comment]
> Please let us know what you find out

`npm rebuild` fixed the issue 🙌
