### ISSUE TITLE
Feature request, help wanted: Integrate new Eclipse JDT  Python script and remove lots of Eclipse JDT code

### ISSUE THREAD

**Issue by joaotavora** [joaotavora/eglot#863]
In https://github.com/eclipse/eclipse.jdt.ls/issues/748, it seems the Eclipse JDT project finally added a Python Script that can start a Java process setting up the JDT server with sane defaults.  

It would be great if this could give rise to an entry in `eglot-server-programs` and allow this deletion:
```diff
diff --git a/eglot.el b/eglot.el
index 7bff005..4d2f2b7 100644
--- a/eglot.el
+++ b/eglot.el
@@ -3013,100 +3013,6 @@ If NOERROR, return predicate, else erroring function."
   (when (eq ?! (aref arg 1)) (aset arg 1 ?^))
   `(,self () (re-search-forward ,(concat "\\=" arg)) (,next)))
 
-
-;;; eclipse-jdt-specific
-;;;
-(defclass eglot-eclipse-jdt (eglot-lsp-server) ()
-  :documentation "Eclipse's Java Development Tools Language Server.")
-
-(cl-defmethod eglot-initialization-options ((server eglot-eclipse-jdt))
-  "Passes through required jdt initialization options."
-  `(:workspaceFolders
-    [,@(cl-delete-duplicates
-        (mapcar #'eglot--path-to-uri
-                (let* ((root (project-root (eglot--project server))))
-                  (cons root
-                        (mapcar
-                         #'file-name-directory
-                         (append
-                          (file-expand-wildcards (concat root "*/pom.xml"))
-                          (file-expand-wildcards (concat root "*/build.gradle"))
-                          (file-expand-wildcards (concat root "*/.project")))))))
-        :test #'string=)]
-    ,@(if-let ((home (or (getenv "JAVA_HOME")
-                         (ignore-errors
-                           (expand-file-name
-                            ".."
-                            (file-name-directory
-                             (file-chase-links (executable-find "javac"))))))))
-          `(:settings (:java (:home ,home)))
-        (ignore (eglot--warn "JAVA_HOME env var not set")))))
-
-(defun eglot--eclipse-jdt-contact (interactive)
-  "Return a contact for connecting to eclipse.jdt.ls server, as a cons cell.
-If INTERACTIVE, prompt user for details."
-  (cl-labels
-      ((is-the-jar
-        (path)
-        (and (string-match-p
-              "org\\.eclipse\\.equinox\\.launcher_.*\\.jar$"
-              (file-name-nondirectory path))
-             (file-exists-p path))))
-    (let* ((classpath (or (getenv "CLASSPATH") path-separator))
-           (cp-jar (cl-find-if #'is-the-jar (split-string classpath path-separator)))
-           (jar cp-jar)
-           (dir
-            (cond
-             (jar (file-name-as-directory
-                   (expand-file-name ".." (file-name-directory jar))))
-             (interactive
-              (expand-file-name
-               (read-directory-name
-                (concat "Path to eclipse.jdt.ls directory (could not"
-                        " find it in CLASSPATH): ")
-                nil nil t)))
-             (t (error "Could not find eclipse.jdt.ls jar in CLASSPATH"))))
-           (repodir
-            (concat dir
-                    "org.eclipse.jdt.ls.product/target/repository/"))
-           (repodir (if (file-directory-p repodir) repodir dir))
-           (config
-            (concat
-             repodir
-             (cond
-              ((string= system-type "darwin") "config_mac")
-              ((string= system-type "windows-nt") "config_win")
-              (t "config_linux"))))
-           (workspace
-            (expand-file-name (md5 (project-root (eglot--current-project)))
-                              (locate-user-emacs-file
-                               "eglot-eclipse-jdt-cache"))))
-      (unless jar
-        (setq jar
-              (cl-find-if #'is-the-jar
-                          (directory-files (concat repodir "plugins") t))))
-      (unless (and jar (file-exists-p jar) (file-directory-p config))
-        (error "Could not find required eclipse.jdt.ls files (build required?)"))
-      (when (and interactive (not cp-jar)
-                 (y-or-n-p (concat "Add path to the server program "
-                                   "to CLASSPATH environment variable?")))
-        (setenv "CLASSPATH" (concat (getenv "CLASSPATH") path-separator jar)))
-      (unless (file-directory-p workspace)
-        (make-directory workspace t))
-      (cons 'eglot-eclipse-jdt
-            (list (executable-find "java")
-                  "-Declipse.application=org.eclipse.jdt.ls.core.id1"
-                  "-Dosgi.bundles.defaultStartLevel=4"
-                  "-Declipse.product=org.eclipse.jdt.ls.core.product"
-                  "-jar" jar
-                  "-configuration" config
-                  "-data" workspace)))))
-
-(cl-defmethod eglot-execute-command
-  ((_server eglot-eclipse-jdt) (_cmd (eql java.apply.workspaceEdit)) arguments)
-  "Eclipse JDT breaks spec and replies with edits as arguments."
-  (mapc #'eglot--apply-workspace-edit arguments))
-
 
 ;;; Obsolete
 ;;;
```

CC: @astoff , @skangas if you know someone who's using this server please tag them here.  If anyone is willing to experiment with this, it'd be most welcome

**Comment by manuel-uberti** [comment]
Hi @joaotavora, I use this server albeit not on big projects (i.e., just small files here and there to test something). I can help testing the changes, if you need.

**Comment by joaotavora** [comment]
That would be most welcome

**Comment by manuel-uberti** [comment]
This is what I tried:
- I removed the `eclipse-jdt-specific` code as you described above
- I added `(java-mode . ("jdtls"))` to `eglot-server-programs` (note: `jdtls` is in my `$PATH`)
- I have this in my `init.el`:
```emacs-lisp
(add-to-list 'load-path "~/code/eglot")
(require 'eglot)
(add-hook 'java-mode-hook #'eglot-ensure)
```
- <kbd>C-x C-f /tmp/Test.java</kbd>

I get this message in `*Messages*`:
```
Error in post-command-hook (#1=(closure ((#2=#:--cl-maybe-connect-- . #1#) (buffer . #<buffer Test.java>) eglot--managed-mode eglot-lsp-context company-tooltip-align-annotations company-backends markdown-fontify-code-blocks-natively t) nil (progn (remove-hook 'post-command-hook #2# nil) (let ((#3=#:G1 buffer)) (if (buffer-live-p #3#) (save-current-buffer (set-buffer #3#) (if eglot--managed-mode nil (apply #'eglot--connect (eglot--guess-contact))))))))): (error "[eglot] -1: Server died")
```
And I have this in `*EGLOT (tmp/java-mode) events*`:
```
[internal] Tue Mar  8 09:26:49 2022:
(:message "Running language server: jdtls")
[client-request] (id:1) Tue Mar  8 09:26:49 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 39424 :rootPath "/tmp/" :rootUri "file:///tmp" :initializationOptions #2=#s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                             ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false :deprecatedSupport t :tagSupport
                                                               (:valueSet
                                                                [1]))
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false :tagSupport
                                             (:valueSet
                                              [1 2])))
                       :experimental #2#)))
[stderr] Traceback (most recent call last):
[stderr]   File "/home/manuel/.bin/jdtls", line 17, in <module>
[stderr]     jdtls.main(sys.argv[1:])
[stderr]   File "/home/manuel/jdt/bin/jdtls.py", line 68, in main
[stderr]     parser.add_argument("--validate-java-version", default=True, action=argparse.BooleanOptionalAction)
[stderr] AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
[internal] Tue Mar  8 09:26:49 2022:
(:message "Connection state changed" :change "exited abnormally with code 1\n")

----------b---y---e---b---y---e----------
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process EGLOT (tmp/java-mode) stderr finished
```

**Comment by nemethf** [comment]
@manuel-uberti, your python seems to be too old for running jdtls.py.  The [documentation] says BooleanOptionalAction was introduced in version 3.9. 

[documentation]: https://docs.python.org/3/library/argparse.html

**Comment by joaotavora** [comment]
@manuel-uberti in addition following @nemethf advice, I advise you to use `M-x eglot` in a Java file instead of `(add-hook 'java-mode-hook #'eglot-ensure)`.

Only add the latter when you've gotten the former working.  It'll make errors easier to debug and nicer error reports.

**Comment by manuel-uberti** [comment]
> @manuel-uberti, your python seems to be too old for running jdtls.py. The [documentation](https://docs.python.org/3/library/argparse.html) says BooleanOptionalAction was introduced in version 3.9.

I think I am running 3.9, TBH:
```
manuel@tux:~$ python --version
Python 3.9.10
```
> @manuel-uberti in addition following @nemethf advice, I advise you to use `M-x eglot` in a Java file instead of `(add-hook 'java-mode-hook #'eglot-ensure)`.
> 
> Only add the latter when you've gotten the former working. It'll make errors easier to debug and nicer error reports.

Done, this is what I get in the `*EGLOT (tmp/java-mode) events*` buffer now:
```
[internal] Tue Mar  8 12:11:30 2022:
(:message "Running language server: jdtls")
[client-request] (id:1) Tue Mar  8 12:11:30 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 51929 :rootPath "/tmp/" :rootUri "file:///tmp" :initializationOptions #2=#s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                             ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false :deprecatedSupport t :tagSupport
                                                               (:valueSet
                                                                [1]))
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false :tagSupport
                                             (:valueSet
                                              [1 2])))
                       :experimental #2#)))
[stderr] Traceback (most recent call last):
[stderr]   File "/home/manuel/.bin/jdtls", line 17, in <module>
[stderr]     jdtls.main(sys.argv[1:])
[stderr]   File "/home/manuel/jdt/bin/jdtls.py", line 68, in main
[stderr]     parser.add_argument("--validate-java-version", default=True, action=argparse.BooleanOptionalAction)
[stderr] AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
[internal] Tue Mar  8 12:11:30 2022:
(:message "Connection state changed" :change "exited abnormally with code 1\n")

----------b---y---e---b---y---e----------
```

**Comment by nemethf** [comment]
> I think I am running 3.9, TBH:

Nevertheless, the error message is quite clear:

> [stderr]   File "/home/manuel/jdt/bin/jdtls.py", line 68, in main
> [stderr]     parser.add_argument("--validate-java-version", default=True, action=argparse.BooleanOptionalAction)
> [stderr] AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

What is the output of `M-! /usr/bin/env python3 --version RET`?

If you can't sort this out, you can try to change `action=argparse.BooleanOptionalAction` to `action='store_true'` in line 68.

**Comment by manuel-uberti** [comment]
> What is the output of `M-! /usr/bin/env python3 --version RET`?

A-ha! It's `Python 3.8.10`. 

I fixed it now, and `eglot` connects just fine. I'll prepare an MR. Thank you, @nemethf!
