### ISSUE TITLE
metals-emacs invalid lsp message

### ISSUE THREAD

**Issue by moberer** [joaotavora/eglot#935]
* Server used: metals-emacs (0.11.2)               
* Emacs version: 28.1            
* Operating system: openSUSE Tumbleweed         
* Eglot version: 1.8            
* Eglot installation method: Doom (straight)      
* Using Doom: Yes               

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)

     
```lisp
[internal] Wed Apr 27 09:56:09 2022:
(:message "Running language server: metals-emacs")
[client-request] (id:1) Wed Apr 27 09:56:09 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 17949 :rootPath "/home/max/projects/aexp-interpreter/" :rootUri "file:///home/max/projects/aexp-interpreter" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                                        ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges t)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t :workspaceFolders t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport t :deprecatedSupport t :tagSupport
                                                               (:valueSet
                                                                [1]))
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false :tagSupport
                                             (:valueSet
                                              [1 2])))
                       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))
                      :workspaceFolders
                      [(:uri "file:///home/max/projects/aexp-interpreter" :name "~/projects/aexp-interpreter/")]))
[server-notification] Wed Apr 27 09:56:10 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:10 INFO  logging to file /home/max/projects/aexp-interpreter/.metals/metals.log"))
[server-notification] Wed Apr 27 09:56:10 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:10 INFO  Started: Metals version 0.11.2 in workspace '/home/max/projects/aexp-interpreter' ."))
[server-notification] Wed Apr 27 09:56:10 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:10 INFO  Parse release: 17.0.3"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  time: initialize in 0.95s"))
[server-reply] (id:1) Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync
            (:openClose t :change 1 :save
                        (:includeText t))
            :hoverProvider t :completionProvider
            (:resolveProvider t :triggerCharacters
                              ["." "*"])
            :signatureHelpProvider
            (:triggerCharacters
             ["(" "[" ","])
            :definitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider
            (:codeActionKinds
             ["quickfix" "refactor" "source.organizeImports"])
            :codeLensProvider
            (:resolveProvider :json-false)
            :documentFormattingProvider t :documentRangeFormattingProvider t :documentOnTypeFormattingProvider
            (:firstTriggerCharacter "\n" :moreTriggerCharacter
                                    ["\""])
            :renameProvider
            (:prepareProvider t)
            :foldingRangeProvider t :executeCommandProvider
            (:commands
             ["analyze-stacktrace" "bsp-switch" "build-connect" "compile-cancel" "compile-cascade" "compile-clean" "copy-worksheet-output" "discover-tests" "extract-member-definition" "generate-bsp-config" "goto-position" "goto-super-method" "goto" "build-import" "insert-inferred-type" "new-scala-file" "new-java-file" "new-scala-project" "presentation-compiler-restart" "reset-choice" "build-restart" "doctor-run" "file-decode" "build-disconnect" "list-build-targets" "sources-scan" "ammonite-start" "debug-adapter-start" "ammonite-stop" "super-method-hierarchy"])
            :selectionRangeProvider t :experimental
            (:rangeHoverProvider t))
           :serverInfo
           (:name "Metals" :version "0.11.2")))
[client-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                            ()))
[client-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///home/max/projects/aexp-interpreter/src/main/scala/Main.scala" :version 0 :languageId "scala" :text "// -----------------------------------------------------\n//               Don't change this file!\n//       The CLI I/O should remain untouched\n//          because we need it for testing!\n// -----------------------------------------------------\n\nimport scala.collection.mutable._\n\nsealed trait EvaluationResult\ncase class EvaluationResultSuccess(value: ExpValue, output: String) extends EvaluationResult\ncase class EvaluationResultError(output: String) extends EvaluationResult\n\nobject Main {\n  def main(args: Array[String]): Unit = {\n    args.toList match {\n      case \"file\"::file::Nil => {\n        evaluateProgram(readFile(file))\n      }\n      case \"evalexpr\"::rest => {\n        evaluateProgram(rest.mkString(\" \"))\n      }\n      case \"parser\"::file::Nil => {\n        val parseResult = ExpParser.parse(readFile(file))\n        if(parseResult.successful) {\n          Console.println(parseResult.get)\n          Console.println(\"==Parse Success==\")\n        } else {\n          Console.println(parseResult.toString)\n          Console.println(\"==Parse Error==\")\n        }\n      }\n      case \"test\"::file::Nil => {\n        evaluateTest(readFile(file), new Queue()) match {\n          case EvaluationResultSuccess(value, output) => Console.println(\"==Result: \" + Utils.format(value) + \" Output: \" + output + \"==\")\n          case EvaluationResultError(_) => Console.println(\"==Parse Error==\")\n        }\n      }\n      case _ => {\n        Console.println(\"Usage:\")\n        Console.println(\"  file [filename] - Loads and interprets the given file.\")\n        Console.println(\"  eval [program] - Evaluates the program code given as argument.\")\n        Console.println(\"  parser [filename] - Loads and parses the given file.\")\n        Console.println(\"  test [filename] - Loads and interprets the given file while buffering all output.\")\n      }\n    }\n  }\n  \n  def readFile(file: String): String = {\n    val source = scala.io.Source.fromFile(file)\n    val fileString = source.mkString\n    source.close()\n    fileString\n  }\n\n  def evaluateProgram(program: String): Unit = {\n    val parseResult = ExpParser.parse(program)\n    if (parseResult.successful) {\n      val result = new Interpreter(() => ExpString(scala.io.StdIn.readLine()), Console.print).interpret(parseResult.get)\n      Console.println(\"\\n\\nResult: \" + Utils.format(result))\n    } else {\n      Console.println(\"\\n\\nError: \" + parseResult.toString)\n    }\n  }\n  \n  def evaluateTest(program: String, input: Queue[ExpValue]): EvaluationResult = {\n    val parseResult = ExpParser.parse(program)\n    val output: StringBuilder = new StringBuilder();\n    if (parseResult.successful) {\n      EvaluationResultSuccess(new Interpreter(() => input.dequeue(), (str: String) => output ++= str).interpret(parseResult.get), output.toString)\n    } else {\n      EvaluationResultError(parseResult.toString)\n    }\n  }\n}\n")))
[client-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings nil))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Flyway Community Edition 8.5.1 by Redgate"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.1"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  "))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Database: jdbc:h2:file:/home/max/projects/aexp-interpreter/.metals/metals (H2 2.0)"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Successfully validated 3 migrations (execution time 00:00.009s)"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Current version of schema \"PUBLIC\": 3"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Schema \"PUBLIC\" is up to date. No migration necessary."))
[server-request] (id:1) Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :id "1" :method "client/registerCapability" :params
          (:registrations
           [(:id "1" :method "workspace/didChangeWatchedFiles" :registerOptions
                 (:watchers
                  [(:globPattern "file:///home/max/projects/aexp-interpreter/*.sbt")
                   (:globPattern "file:///home/max/projects/aexp-interpreter/pom.xml")
                   (:globPattern "file:///home/max/projects/aexp-interpreter/*.sc")
                   (:globPattern "file:///home/max/projects/aexp-interpreter/*?.gradle")
                   (:globPattern "file:///home/max/projects/aexp-interpreter/*.gradle.kts")
                   (:globPattern "file:///home/max/projects/aexp-interpreter/project/*.{scala,sbt}")
                   (:globPattern "file:///home/max/projects/aexp-interpreter/project/project/*.{scala,sbt}")
                   (:globPattern "file:///home/max/projects/aexp-interpreter/project/build.properties")]))]))
[client-reply] (id:1) Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :id "1" :result nil)
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Attempting to connect to the build server..."))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  skipping build import with status 'Installed'"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/max/projects/aexp-interpreter/.metals/bsp.trace.json or /home/max/.cache/metals/bsp.trace.json"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Attempting to connect to the build server..."))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/max/projects/aexp-interpreter/project/.metals/bsp.trace.json or /home/max/.cache/metals/bsp.trace.json"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  time: Connected to build server in 0.11s"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:11 INFO  Connected to Build server: Bloop v1.5.0"))
[server-notification] Wed Apr 27 09:56:11 2022:
(:jsonrpc "2.0" :method "metals/executeClientCommand" :params
          (:command "metals-doctor-reload" :arguments
                    ["<h1 >Metals Doctor</h1><p >Build server currently being used is Bloop v1.5.0.</p><p >These are the installed build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.</p><table ><thead ><tr ><th >Build target</th><th >Type</th><th >Diagnostics</th><th >Interactive</th><th >Semanticdb</th><th >Debugging</th><th >Java support</th><th >Recommendation</th></tr></thead><tbody ><tr ><td >aexp-interpreter</td><td >Scala 2.13.8</td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td ></td></tr><tr ><td >aexp-interpreter-test</td><td >Scala 2.13.8</td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td ></td></tr><tr ><td >aexp-interpreter-build</td><td >sbt 1.6.2</td><td style='text-align: center'>&#9888;&#65039; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#9989; </td><td style='text-align: center'>&#10060;</td><td style='text-align: center'>&#9989; </td><td >Diagnostics and debugging for sbt are not supported currently.</td></tr></tbody></table><div ><p >Diagnostics:</p><ul ><li >&#9989;  - diagnostics correctly being reported by the build server</li><li >&#9888;&#65039;  - only syntactic errors being reported</li></ul></div><div ><p >Interactive features (completions, hover):</p><ul ><li >&#9989;  - supported Scala version</li></ul></div><div ><p >Semanticdb features (references, renames, go to implementation):</p><ul ><li >&#9989;  - build tool automatically creating needed semanticdb files</li></ul></div><div ><p >Debugging (run/test, breakpoints, evaluation):</p><ul ><li >&#9989;  - users can run or test their code with debugging capabilities</li><li >&#10060; - the tool does not support debugging in this target</li></ul></div><div ><p >Java Support:</p><ul ><li >&#9989;  - working non-interactive features (references, rename etc.)</li></ul></div>"]))
[server-notification] Wed Apr 27 09:56:13 2022:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 4 :message "2022.04.27 09:56:13 INFO  time: indexed workspace in 1.33s"))
[client-request] (id:2) Wed Apr 27 09:56:23 2022:
(:jsonrpc "2.0" :id 2 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///home/max/projects/aexp-interpreter/src/main/scala/Main.scala")
           :position
           (:line 64 :character 13)))
[client-request] (id:3) Wed Apr 27 09:56:23 2022:
(:jsonrpc "2.0" :id 3 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///home/max/projects/aexp-interpreter/src/main/scala/Main.scala")
           :position
           (:line 64 :character 13)))
[client-request] (id:4) Wed Apr 27 09:56:23 2022:
(:jsonrpc "2.0" :id 4 :method "textDocument/documentHighlight" :params
          (:textDocument
           (:uri "file:///home/max/projects/aexp-interpreter/src/main/scala/Main.scala")
           :position
           (:line 64 :character 13)))
[server-reply] (id:4) Wed Apr 27 09:56:23 2022:
(:jsonrpc "2.0" :id 4 :result
          [(:range
            (:start
             (:line 32 :character 8)
             :end
             (:line 32 :character 20))
            :kind 2)
           (:range
            (:start
             (:line 64 :character 6)
             :end
             (:line 64 :character 18))
            :kind 3)])
[server-reply] (id:2) Wed Apr 27 09:56:23 2022:
(:jsonrpc "2.0" :id 2 :result
          (:signatures
           []))
[server-reply] (id:3) Wed Apr 27 09:56:23 2022:
(:jsonrpc "2.0" :id 3 :result
          (:contents
           (:kind "markdown" :value "```scala\ndef evaluateTest(program: String, input: Queue[ExpValue]): EvaluationResult\n```")
           :range
           (:start
            (:line 64 :character 2)
            :end
            (:line 72 :character 3))))

```
    
#### Backtrace (mandatory, unless no error message seen or heard):

     
There does not happen any recognizable problem / backtrace in Emacs.
However, the language server (metals-emacs) logs an exception:

```
2022.04.27 09:45:34 INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/max/projects/aexp-interpreter/.metals/lsp.trace.json or /home/max/.cache/metals/lsp.trace.json[0m
2022.04.27 09:45:34 INFO  logging to file /home/max/projects/aexp-interpreter/.metals/metals.log[0m
2022.04.27 09:45:34 INFO  Started: Metals version 0.11.2 in workspace '/home/max/projects/aexp-interpreter' .[0m
2022.04.27 09:45:34 INFO  Parse release: 17.0.3[0m
2022.04.27 09:45:35 INFO  time: initialize in 0.97s[0m
2022.04.27 09:45:35 INFO  Attempting to connect to the build server...[0m
Apr. 27, 2022 9:45:35 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNUNG: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {}
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "org.eclipse.lsp4j.DidChangeConfigurationParams.getSettings()" is null
	at scala.meta.internal.metals.MetalsLanguageServer.didChangeConfiguration(MetalsLanguageServer.scala:1252)
	... 16 more

2022.04.27 09:45:35 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/max/projects/aexp-interpreter/.metals/bsp.trace.json or /home/max/.cache/metals/bsp.trace.json[0m
2022.04.27 09:45:35 INFO  Attempting to connect to the build server...[0m
2022.04.27 09:45:35 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/max/projects/aexp-interpreter/project/.metals/bsp.trace.json or /home/max/.cache/metals/bsp.trace.json[0m
2022.04.27 09:45:35 INFO  time: Connected to build server in 0.1s[0m
2022.04.27 09:45:35 INFO  Connected to Build server: Bloop v1.5.0[0m
2022.04.27 09:45:36 INFO  running '/usr/lib64/jvm/java-17-openjdk/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals17512682869846610523/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
2022.04.27 09:45:36 INFO  [info] welcome to sbt 1.6.2 (N/A Java 17.0.3)[0m
2022.04.27 09:45:36 INFO  [info] loading settings for project aexp-interpreter-build-build from metals.sbt ...[0m
2022.04.27 09:45:36 INFO  [info] loading project definition from /home/max/projects/aexp-interpreter/project/project[0m
2022.04.27 09:45:38 INFO  [info] loading settings for project aexp-interpreter-build from metals.sbt ...[0m
2022.04.27 09:45:38 INFO  [info] loading project definition from /home/max/projects/aexp-interpreter/project[0m
2022.04.27 09:45:38 INFO  time: indexed workspace in 3.08s[0m
2022.04.27 09:45:39 INFO  [success] Generated .bloop/aexp-interpreter-build.json[0m
2022.04.27 09:45:39 INFO  [success] Total time: 1 s, completed 27.04.2022, 09:45:39[0m
2022.04.27 09:45:39 INFO  [info] loading settings for project aexp-interpreter from build.sbt ...[0m
2022.04.27 09:45:39 INFO  [info] set current project to SWP Interpreter (in build file:/home/max/projects/aexp-interpreter/)[0m
2022.04.27 09:45:39 INFO  [success] Generated .bloop/aexp-interpreter.json[0m
2022.04.27 09:45:39 INFO  [success] Generated .bloop/aexp-interpreter-test.json[0m
2022.04.27 09:45:39 INFO  [success] Total time: 0 s, completed 27.04.2022, 09:45:39[0m
2022.04.27 09:45:39 INFO  time: ran 'sbt bloopInstall' in 3.75s[0m
2022.04.27 09:45:39 INFO  Disconnecting from Bloop session...[0m
2022.04.27 09:45:39 INFO  Shut down connection with build server.[0m
2022.04.27 09:45:39 INFO  Shut down connection with build server.[0m
2022.04.27 09:45:39 INFO  Attempting to connect to the build server...[0m
2022.04.27 09:45:40 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/max/projects/aexp-interpreter/.metals/bsp.trace.json or /home/max/.cache/metals/bsp.trace.json[0m
2022.04.27 09:45:40 INFO  Attempting to connect to the build server...[0m
2022.04.27 09:45:40 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/max/projects/aexp-interpreter/project/.metals/bsp.trace.json or /home/max/.cache/metals/bsp.trace.json[0m
2022.04.27 09:45:40 INFO  time: Connected to build server in 0.11s[0m
2022.04.27 09:45:40 INFO  Connected to Build server: Bloop v1.5.0[0m
2022.04.27 09:45:41 INFO  time: indexed workspace in 1.05s[0m
```

   
#### Minimal configuration (mandatory)

     
 ```sh
 # Type this in a shell to start an Emacs with Eglot configured
 $ emacs -Q -f package-initialize
 ```
 
 
 
 ```lisp
 ;; Example of a minimal configuration
 ;;
(package-install 'scala-mode)
(package-install 'eglot)
 
;; open scala file

(eglot)
  ```
 
## Problem description

It is assumed that Eglot sends an invalid lsp message, causing the server to throw an exception.
See this bug report: [https://github.com/scalameta/metals/issues/3870](https://github.com/scalameta/metals/issues/3870)

**Comment by joaotavora** [comment]
Let's convert this to a discussion.  The point of issues in the Eglot bug tracker is to contain a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

I'll update the bug reporting template very soon to make this clear.
