### ISSUE TITLE
textDocument/onTypeFormatting uses inconsistent ch / position when electric-pair-mode is enabled

### ISSUE THREAD

**Issue by Fybe** [joaotavora/eglot#979]
1. Open any rust file with rust-analyzer. You may need to run `cargo init`, so rust-analyzer discovers the workspace, and simply open `src/main.rs`.

2. Turn on `electric-pair-mode`
3. Type the following:
```rust
fn main() {
```

4. Compare the following two messages inconsistent messages
```lisp
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/finn/tmp/src/main.rs" :version 23)
           :contentChanges
           [(:range
             (:start
              (:line 0 :character 10)
              :end
              (:line 0 :character 11))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 0 :character 10)
              :end
              (:line 0 :character 10))
             :rangeLength 0 :text "{")
            (:range
             (:start
              (:line 0 :character 11)
              :end
              (:line 0 :character 11))
             :rangeLength 0 :text "}")]))
```
and
```lisp
(:jsonrpc "2.0" :id 6 :method "textDocument/onTypeFormatting" :params
          (:textDocument
           (:uri "file:///home/finn/tmp/src/main.rs")
           :options
           (:tabSize 2 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t)
           :position
           (:line 0 :character 12)
           :ch "{"))
[stderr] Panic context:
[stderr] > 
[stderr] version: 0.0.0 (eb9b36075 2022-06-18)
[stderr] request: textDocument/onTypeFormatting DocumentOnTypeFormattingParams {
[stderr]     text_document_position: TextDocumentPositionParams {
[stderr]         text_document: TextDocumentIdentifier {
[stderr]             uri: Url {
[stderr]                 scheme: "file",
[stderr]                 cannot_be_a_base: false,
[stderr]                 username: "",
[stderr]                 password: None,
[stderr]                 host: None,
[stderr]                 port: None,
[stderr]                 path: "/home/finn/tmp/src/main.rs",
[stderr]                 query: None,
[stderr]                 fragment: None,
[stderr]             },
[stderr]         },
[stderr]         position: Position {
[stderr]             line: 0,
[stderr]             character: 12,
[stderr]         },
[stderr]     },
[stderr]     ch: "{",
[stderr]     options: FormattingOptions {
[stderr]         tab_size: 2,
[stderr]         insert_spaces: true,
[stderr]         properties: {},
[stderr]         trim_trailing_whitespace: None,
[stderr]         insert_final_newline: Some(
[stderr]             true,
[stderr]         ),
[stderr]         trim_final_newlines: Some(
[stderr]             true,
[stderr]         ),
[stderr]     },
[stderr] }
[stderr] 
[stderr] thread 'Worker' panicked at 'assertion failed: !!text[usize::from(position.offset)..].starts_with(char_typed)', crates/rust-analyzer/src/handlers.rs:291:8
[stderr] stack backtrace:
[server-reply] (id:6) ERROR Wed Jun 22 14:32:31 2022:
(:jsonrpc "2.0" :id 6 :error
          (:code -32603 :message "request handler panicked: assertion failed: !!text[usize::from(position.offset)..].starts_with(char_typed)"))
[stderr]    0: rust_begin_unwind
[stderr]    1: core::panicking::panic_fmt
[stderr]    2: rust_analyzer::handlers::handle_on_type_formatting
[stderr]    3: std::panicking::try
[stderr]    4: <F as threadpool::FnBox>::call_box
[stderr] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Here are two related issues, that seem to be dealing with the exact same problem: [issue in vs-code](https://github.com/microsoft/vscode/issues/131700), [issue in rust-analyzer](https://github.com/rust-lang/rust-analyzer/issues/10002)

<details>
<summary>
System info, transcript, etc...
</summary>

* Server used:               rust-analyzer (commit eb9b36075) 
* Emacs version:             29.0.50 
* Operating system:          Fedora Linux 36 
* Eglot version:             1.8 (commit 132ea08f97f94ad2e050fc8d1628ecb41de7229a) 
* Eglot installation method: straight.el      
* Using Doom:                no 

#### Backtrace:

```lisp
(jsonrpc-error "request id=17 failed:" (jsonrpc-error-code . -32603) (jsonrpc-error-message . "request handler panicked: assertion failed: !!text...") (jsonrpc-error-data))
  signal(jsonrpc-error ("request id=17 failed:" (jsonrpc-error-code . -32603) (jsonrpc-error-message . "request handler panicked: assertion failed: !!text...") (jsonrpc-error-data)))
  #<subr jsonrpc-request>(#<eglot-lsp-server eglot-lsp-server-d40fc8> :textDocument/onTypeFormatting (:textDocument (:uri "file:///home/finn/Programming/tmp/main.rs") :options (:tabSize 2 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t) :position (:line 0 :character 12) :ch "{") :deferred :textDocument/onTypeFormatting)
  apply(#<subr jsonrpc-request> (#<eglot-lsp-server eglot-lsp-server-d40fc8> :textDocument/onTypeFormatting (:textDocument (:uri "file:///home/finn/Programming/tmp/main.rs") :options (:tabSize 2 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t) :position (:line 0 :character 12) :ch "{") :deferred :textDocument/onTypeFormatting))
  jsonrpc-request(#<eglot-lsp-server eglot-lsp-server-d40fc8> :textDocument/onTypeFormatting (:textDocument (:uri "file:///home/finn/Programming/tmp/main.rs") :options (:tabSize 2 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t) :position (:line 0 :character 12) :ch "{") :deferred :textDocument/onTypeFormatting)
  eglot-format(13 nil 123)
  eglot--post-self-insert-hook()
  electric-pair--insert(125)
  electric-pair-post-self-insert-function()
  self-insert-command(1 123)
  funcall-interactively(self-insert-command 1 123)
  command-execute(self-insert-command)

```

#### LSP transcript

     

```lisp
[client-request] (id:1) Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 101378 :rootPath "/home/finn/Programming/tmp/" :rootUri "file:///home/finn/Programming/tmp" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                       ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges t)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t :workspaceFolders t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false :deprecatedSupport t :tagSupport
                                                               (:valueSet
                                                                [1]))
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)
                                               :activeParameterSupport t))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :declaration
                        (:dynamicRegistration :json-false :linkSupport t)
                        :implementation
                        (:dynamicRegistration :json-false :linkSupport t)
                        :typeDefinition
                        (:dynamicRegistration :json-false :linkSupport t)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false :codeDescriptionSupport :json-false :tagSupport
                                             (:valueSet
                                              [1 2])))
                       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))
                      :workspaceFolders
                      [(:uri "file:///home/finn/Programming/tmp" :name "~/Programming/tmp/")]))
[server-reply] (id:1) Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync
            (:openClose t :change 2 :save nil)
            :selectionRangeProvider t :hoverProvider t :completionProvider
            (:triggerCharacters
             [":" "." "'" "("])
            :signatureHelpProvider
            (:triggerCharacters
             ["(" "," "<"])
            :definitionProvider t :typeDefinitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider
            (:codeActionKinds
             ["" "quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite"]
             :resolveProvider t)
            :codeLensProvider
            (:resolveProvider t)
            :documentFormattingProvider t :documentRangeFormattingProvider :json-false :documentOnTypeFormattingProvider
            (:firstTriggerCharacter "=" :moreTriggerCharacter
                                    ["." ">" "{"])
            :renameProvider
            (:prepareProvider t)
            :foldingRangeProvider t :declarationProvider t :workspace
            (:fileOperations
             (:willRename
              (:filters
               [(:scheme "file" :pattern
                         (:glob "**/*.rs" :matches "file"))
                (:scheme "file" :pattern
                         (:glob "**" :matches "folder"))])))
            :callHierarchyProvider t :semanticTokensProvider
            (:legend
             (:tokenTypes
              ["comment" "keyword" "string" "number" "regexp" "operator" "namespace" "type" "struct" "class" "interface" "enum" "enumMember" "typeParameter" "function" "method" "property" "macro" "variable" "parameter" "angle" "arithmetic" "attribute" "attributeBracket" "bitwise" "boolean" "brace" "bracket" "builtinAttribute" "builtinType" "character" "colon" "comma" "comparison" "constParameter" "derive" "dot" "escapeSequence" "formatSpecifier" "generic" "label" "lifetime" "logical" "macroBang" "operator" "parenthesis" "punctuation" "selfKeyword" "selfTypeKeyword" "semicolon" "typeAlias" "toolModule" "union" "unresolvedReference"]
              :tokenModifiers
              ["documentation" "declaration" "definition" "static" "abstract" "deprecated" "readonly" "defaultLibrary" "async" "attribute" "callable" "constant" "consuming" "controlFlow" "crateRoot" "injected" "intraDocLink" "library" "mutable" "public" "reference" "trait" "unsafe"])
             :range t :full
             (:delta t))
            :inlayHintProvider
            (:resolveProvider t)
            :experimental
            (:externalDocs t :hoverRange t :joinLines t :matchingBrace t :moveItem t :onEnter t :openCargoToml t :parentModule t :runnables
                           (:kinds
                            ["cargo"])
                           :ssr t :workspaceSymbolScopeKindFiltering t))
           :serverInfo
           (:name "rust-analyzer" :version "0.0.0 (eb9b36075 2022-06-18)")))
[client-notification] Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                            ()))
[client-notification] Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs" :version 0 :languageId "rust" :text "\n")))
[client-notification] Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings
           (:pylsp
            ((plugins
              (pycodestyle
               (select .
                       ["B950"])
               (ignore .
                       ["E203" "E501"]))
              (black
               (enabled . t)
               (preview . t))
              (yapf
               (enabled)))))))
[server-request] (id:0) Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :id 0 :method "workspace/configuration" :params
          (:items
           [(:section "rust-analyzer")]))
[client-reply] (id:0) Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :id 0 :result
          [nil])
[server-request] (id:1) Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :id 1 :method "client/registerCapability" :params
          (:registrations
           [(:id "workspace/didChangeWatchedFiles" :method "workspace/didChangeWatchedFiles" :registerOptions
                 (:watchers
                  [(:globPattern "/home/finn/Programming/tmp/**/*.rs")
                   (:globPattern "/home/finn/Programming/tmp/**/Cargo.toml")
                   (:globPattern "/home/finn/Programming/tmp/**/Cargo.lock")]))]))
[client-reply] (id:1) Wed Jun 22 13:47:20 2022:
(:jsonrpc "2.0" :id 1 :result nil)
[server-notification] Wed Jun 22 13:47:21 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                [(:range
                  (:start
                   (:line 0 :character 1)
                   :end
                   (:line 0 :character 1))
                  :severity 1 :code "E0601" :codeDescription
                  (:href "https://doc.rust-lang.org/error-index.html#E0601")
                  :source "rustc" :message "`main` function not found in crate `tmp`\nconsider adding a `main` function to `main.rs`")]
                :version 0))
[server-notification] Wed Jun 22 13:47:21 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                []
                :version 0))
[server-notification] Wed Jun 22 13:47:21 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                [(:range
                  (:start
                   (:line 0 :character 1)
                   :end
                   (:line 0 :character 1))
                  :severity 1 :code "E0601" :codeDescription
                  (:href "https://doc.rust-lang.org/error-index.html#E0601")
                  :source "rustc" :message "`main` function not found in crate `tmp`\nconsider adding a `main` function to `main.rs`")]
                :version 0))
[server-request] (id:2) Wed Jun 22 13:47:21 2022:
(:jsonrpc "2.0" :id 2 :method "client/registerCapability" :params
          (:registrations
           [(:id "workspace/didChangeWatchedFiles" :method "workspace/didChangeWatchedFiles" :registerOptions
                 (:watchers
                  [(:globPattern "/home/finn/Programming/tmp/**/*.rs")
                   (:globPattern "/home/finn/Programming/tmp/**/Cargo.toml")
                   (:globPattern "/home/finn/Programming/tmp/**/Cargo.lock")]))]))
[client-reply] (id:2) Wed Jun 22 13:47:21 2022:
(:jsonrpc "2.0" :id 2 :result nil)
[server-notification] Wed Jun 22 13:47:21 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                []
                :version 0))
[server-notification] Wed Jun 22 13:47:21 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                [(:range
                  (:start
                   (:line 0 :character 1)
                   :end
                   (:line 0 :character 1))
                  :severity 1 :code "E0601" :codeDescription
                  (:href "https://doc.rust-lang.org/error-index.html#E0601")
                  :source "rustc" :message "`main` function not found in crate `tmp`\nconsider adding a `main` function to `main.rs`")]
                :version 0))
[server-notification] Wed Jun 22 13:47:24 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                [(:range
                  (:start
                   (:line 0 :character 1)
                   :end
                   (:line 0 :character 1))
                  :severity 1 :code "E0601" :codeDescription
                  (:href "https://doc.rust-lang.org/error-index.html#E0601")
                  :source "rustc" :message "`main` function not found in crate `tmp`\nconsider adding a `main` function to `main.rs`")]
                :version 0))
[client-request] (id:2) Wed Jun 22 13:47:38 2022:
(:jsonrpc "2.0" :id 2 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 0)))
[client-request] (id:3) Wed Jun 22 13:47:38 2022:
(:jsonrpc "2.0" :id 3 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 0)))
[client-request] (id:4) Wed Jun 22 13:47:38 2022:
(:jsonrpc "2.0" :id 4 :method "textDocument/documentHighlight" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 0)))
[server-reply] (id:2) Wed Jun 22 13:47:38 2022:
(:jsonrpc "2.0" :id 2 :result nil)
[server-reply] (id:3) Wed Jun 22 13:47:38 2022:
(:jsonrpc "2.0" :id 3 :result nil)
[server-reply] (id:4) Wed Jun 22 13:47:38 2022:
(:jsonrpc "2.0" :id 4 :result nil)
[client-notification] Wed Jun 22 13:47:38 2022:
(:jsonrpc "2.0" :method "workspace/didChangeWatchedFiles" :params
          (:changes
           [(:uri "file:///home/finn/Programming/tmp/finn@zen.101378%3A1655891007" :type 1)]))
[client-notification] Wed Jun 22 13:47:39 2022:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs" :version 7)
           :contentChanges
           [(:range
             (:start
              (:line 0 :character 0)
              :end
              (:line 0 :character 0))
             :rangeLength 0 :text "f")
            (:range
             (:start
              (:line 0 :character 1)
              :end
              (:line 0 :character 1))
             :rangeLength 0 :text "n")
            (:range
             (:start
              (:line 0 :character 2)
              :end
              (:line 0 :character 2))
             :rangeLength 0 :text " ")
            (:range
             (:start
              (:line 0 :character 3)
              :end
              (:line 0 :character 3))
             :rangeLength 0 :text "m")
            (:range
             (:start
              (:line 0 :character 4)
              :end
              (:line 0 :character 4))
             :rangeLength 0 :text "a")
            (:range
             (:start
              (:line 0 :character 5)
              :end
              (:line 0 :character 5))
             :rangeLength 0 :text "i")
            (:range
             (:start
              (:line 0 :character 6)
              :end
              (:line 0 :character 6))
             :rangeLength 0 :text "n")]))
[client-request] (id:5) Wed Jun 22 13:47:39 2022:
(:jsonrpc "2.0" :id 5 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 7)))
[client-request] (id:6) Wed Jun 22 13:47:39 2022:
(:jsonrpc "2.0" :id 6 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 7)))
[client-request] (id:7) Wed Jun 22 13:47:39 2022:
(:jsonrpc "2.0" :id 7 :method "textDocument/documentHighlight" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 7)))
[server-reply] (id:5) Wed Jun 22 13:47:39 2022:
(:jsonrpc "2.0" :id 5 :result nil)
[server-reply] (id:7) Wed Jun 22 13:47:39 2022:
(:jsonrpc "2.0" :id 7 :result
          [(:range
            (:start
             (:line 0 :character 3)
             :end
             (:line 0 :character 7)))])
[server-reply] (id:6) Wed Jun 22 13:47:39 2022:
(:jsonrpc "2.0" :id 6 :result
          (:contents
           (:kind "markdown" :value "\n```rust\ntmp\n```\n\n```rust\nfn main()\n```")
           :range
           (:start
            (:line 0 :character 3)
            :end
            (:line 0 :character 7))))
[server-notification] Wed Jun 22 13:47:40 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                [(:range
                  (:start
                   (:line 0 :character 7)
                   :end
                   (:line 0 :character 7))
                  :severity 1 :code "syntax-error" :codeDescription
                  (:href "https://rust-analyzer.github.io/manual.html#syntax-error")
                  :source "rust-analyzer" :message "Syntax Error: expected function arguments")
                 (:range
                  (:start
                   (:line 0 :character 7)
                   :end
                   (:line 0 :character 7))
                  :severity 1 :code "syntax-error" :codeDescription
                  (:href "https://rust-analyzer.github.io/manual.html#syntax-error")
                  :source "rust-analyzer" :message "Syntax Error: expected a block")
                 (:range
                  (:start
                   (:line 0 :character 1)
                   :end
                   (:line 0 :character 1))
                  :severity 1 :code "E0601" :codeDescription
                  (:href "https://doc.rust-lang.org/error-index.html#E0601")
                  :source "rustc" :message "`main` function not found in crate `tmp`\nconsider adding a `main` function to `main.rs`")]
                :version 7))
[client-notification] Wed Jun 22 13:47:40 2022:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs" :version 17)
           :contentChanges
           [(:range
             (:start
              (:line 0 :character 7)
              :end
              (:line 0 :character 7))
             :rangeLength 0 :text "(")
            (:range
             (:start
              (:line 0 :character 7)
              :end
              (:line 0 :character 8))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 0 :character 7)
              :end
              (:line 0 :character 7))
             :rangeLength 0 :text "(")
            (:range
             (:start
              (:line 0 :character 8)
              :end
              (:line 0 :character 8))
             :rangeLength 0 :text ")")
            (:range
             (:start
              (:line 0 :character 8)
              :end
              (:line 0 :character 8))
             :rangeLength 0 :text ")")
            (:range
             (:start
              (:line 0 :character 8)
              :end
              (:line 0 :character 9))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 0 :character 8)
              :end
              (:line 0 :character 8))
             :rangeLength 0 :text ")")
            (:range
             (:start
              (:line 0 :character 8)
              :end
              (:line 0 :character 9))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 0 :character 9)
              :end
              (:line 0 :character 9))
             :rangeLength 0 :text " ")
            (:range
             (:start
              (:line 0 :character 10)
              :end
              (:line 0 :character 10))
             :rangeLength 0 :text "{")]))
[client-request] (id:8) Wed Jun 22 13:47:40 2022:
(:jsonrpc "2.0" :id 8 :method "textDocument/onTypeFormatting" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :options
           (:tabSize 2 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t)
           :position
           (:line 0 :character 11)
           :ch "{"))
[server-reply] (id:8) Wed Jun 22 13:47:40 2022:
(:jsonrpc "2.0" :id 8 :result nil)
[client-notification] Wed Jun 22 13:47:40 2022:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs" :version 20)
           :contentChanges
           [(:range
             (:start
              (:line 0 :character 10)
              :end
              (:line 0 :character 11))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 0 :character 10)
              :end
              (:line 0 :character 10))
             :rangeLength 0 :text "{")
            (:range
             (:start
              (:line 0 :character 11)
              :end
              (:line 0 :character 11))
             :rangeLength 0 :text "}")]))
[client-request] (id:9) Wed Jun 22 13:47:40 2022:
(:jsonrpc "2.0" :id 9 :method "textDocument/onTypeFormatting" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :options
           (:tabSize 2 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t)
           :position
           (:line 0 :character 12)
           :ch "{"))
[stderr] Panic context:
[stderr] > 
[stderr] version: 0.0.0 (eb9b36075 2022-06-18)
[stderr] request: textDocument/onTypeFormatting DocumentOnTypeFormattingParams {
[stderr]     text_document_position: TextDocumentPositionParams {
[stderr]         text_document: TextDocumentIdentifier {
[stderr]             uri: Url {
[stderr]                 scheme: "file",
[stderr]                 cannot_be_a_base: false,
[stderr]                 username: "",
[stderr]                 password: None,
[stderr]                 host: None,
[stderr]                 port: None,
[stderr]                 path: "/home/finn/Programming/tmp/main.rs",
[stderr]                 query: None,
[stderr]                 fragment: None,
[stderr]             },
[stderr]         },
[stderr]         position: Position {
[stderr]             line: 0,
[stderr]             character: 12,
[stderr]         },
[stderr]     },
[stderr]     ch: "{",
[stderr]     options: FormattingOptions {
[stderr]         tab_size: 2,
[stderr]         insert_spaces: true,
[stderr]         properties: {},
[stderr]         trim_trailing_whitespace: None,
[stderr]         insert_final_newline: Some(
[stderr]             true,
[stderr]         ),
[stderr]         trim_final_newlines: Some(
[stderr]             true,
[stderr]         ),
[stderr]     },
[stderr] }
[stderr] 
[stderr] thread 'Worker' panicked at 'assertion failed: !!text[usize::from(position.offset)..].starts_with(char_typed)', crates/rust-analyzer/src/handlers.rs:291:8
[stderr] stack backtrace:
[stderr]    0: rust_begin_unwind
[stderr]    0: rust_begin_unwind
[server-reply] (id:9) ERROR Wed Jun 22 13:47:40 2022:
(:jsonrpc "2.0" :id 9 :error
          (:code -32603 :message "request handler panicked: assertion failed: !!text[usize::from(position.offset)..].starts_with(char_typed)"))
[stderr]    1: core::panicking::panic_fmt
[stderr]    2: rust_analyzer::handlers::handle_on_type_formatting
[stderr]    3: std::panicking::try
[stderr]    4: <F as threadpool::FnBox>::call_box
[stderr] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[client-request] (id:10) Wed Jun 22 13:47:41 2022:
(:jsonrpc "2.0" :id 10 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 11)))
[client-request] (id:11) Wed Jun 22 13:47:41 2022:
(:jsonrpc "2.0" :id 11 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 11)))
[client-request] (id:12) Wed Jun 22 13:47:41 2022:
(:jsonrpc "2.0" :id 12 :method "textDocument/documentHighlight" :params
          (:textDocument
           (:uri "file:///home/finn/Programming/tmp/main.rs")
           :position
           (:line 0 :character 11)))
[server-reply] (id:10) Wed Jun 22 13:47:41 2022:
(:jsonrpc "2.0" :id 10 :result nil)
[server-reply] (id:12) Wed Jun 22 13:47:41 2022:
(:jsonrpc "2.0" :id 12 :result nil)
[server-reply] (id:11) Wed Jun 22 13:47:42 2022:
(:jsonrpc "2.0" :id 11 :result
          (:contents
           (:kind "markdown" :value "```rust\n()\n```")
           :range
           (:start
            (:line 0 :character 10)
            :end
            (:line 0 :character 12))))
[server-notification] Wed Jun 22 13:47:42 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/finn/Programming/tmp/main.rs" :diagnostics
                [(:range
                  (:start
                   (:line 0 :character 1)
                   :end
                   (:line 0 :character 1))
                  :severity 1 :code "E0601" :codeDescription
                  (:href "https://doc.rust-lang.org/error-index.html#E0601")
                  :source "rustc" :message "`main` function not found in crate `tmp`\nconsider adding a `main` function to `main.rs`")]
                :version 20))

```
    

</details>

**Comment by joaotavora** [comment]
Sorry to be looking at this so late.  I'm not sure there is an inconsistency in the Eglot -> LSP messaging, 

here's from the spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_onTypeFormatting
```
/**
	 * The position around which the on type formatting should happen.
	 * This is not necessarily the exact position where the character denoted
	 * by the property `ch` got typed.
	 */
	position: [Position](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position);
```

At any rate, I tried with `rust-analyzer` today and it doesn't seem to crash like it presumably used to:

```
[client-request] (id:8) Sun Mar 26 20:15:45 2023:
(:jsonrpc "2.0" :id 8 :method "textDocument/onTypeFormatting" :params
          (:textDocument
           (:uri "file:///home/capitaomorte/Source/Rust/bevy/src/lib.rs")
           :options
           (:tabSize 8 :insertSpaces t :insertFinalNewline t :trimFinalNewlines t)
           :position
           (:line 51 :character 9)
           :ch "{"))
[stderr] [ERROR rust_analyzer::handlers] assertion failed: !!text[usize::from(position.offset)..].starts_with(char_typed)    
```

I think that assertion doesn't make sense, but it doesn't seem to be phased by it anyway.  So problem gone?  I'm closing, but feel free to ask me to reopen.
